id: challenge-generator
namespace: cademy.content

triggers:
  - id: daily_schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "0 2 * * *"

tasks:
  - id: generate_challenge_spec
    type: io.kestra.plugin.scripts.python.Script
    runner: DOCKER
    docker:
      image: python:3.11-slim
    script: |
      import json
      import random
      from datetime import datetime
      
      shapes = ["cube", "sphere", "cylinder", "cone"]
      operations = ["union", "subtract", "intersect"]
      difficulties = ["beginner", "intermediate", "advanced"]
      
      challenge_id = f"daily_{datetime.now().strftime('%Y%m%d')}"
      difficulty = random.choice(difficulties)
      
      challenge = {
          "id": challenge_id,
          "title": f"Daily Challenge - {datetime.now().strftime('%B %d, %Y')}",
          "difficulty": difficulty,
          "description": "Create a model using the specified constraints",
          "requirements": {
              "min_objects": random.randint(2, 5),
              "required_shapes": random.sample(shapes, k=random.randint(2, 3)),
              "operations": random.sample(operations, k=random.randint(1, 2))
          },
          "target_model": {
              "objects": [],
              "operations": []
          },
          "hints": [
              "Start with basic shapes",
              "Use boolean operations effectively",
              "Check alignment carefully"
          ],
          "time_limit": 1800,
          "points": 100 if difficulty == "advanced" else 50
      }
      
      print(json.dumps(challenge))

  - id: validate_challenge
    type: io.kestra.plugin.scripts.python.Script
    runner: DOCKER
    docker:
      image: python:3.11-slim
    script: |
      import json
      
      challenge = json.loads('''{{ outputs.generate_challenge_spec.vars.challenge }}''')
      
      # Validation rules
      valid = (
          challenge["requirements"]["min_objects"] > 0 and
          len(challenge["requirements"]["required_shapes"]) > 0 and
          challenge["points"] > 0
      )
      
      print(json.dumps({"valid": valid, "challenge": challenge}))

  - id: store_challenge
    type: io.kestra.plugin.scripts.python.Script
    runner: DOCKER
    docker:
      image: python:3.11-slim
    beforeCommands:
      - pip install requests
    script: |
      import json
      import requests
      
      validation = json.loads('''{{ outputs.validate_challenge.vars }}''')
      
      if validation["valid"]:
          response = requests.post(
              "http://backend:3001/api/challenges/create",
              json=validation["challenge"]
          )
          print(f"Challenge stored: {response.status_code}")
      else:
          print("Challenge validation failed")

outputs:
  - id: generated_challenge
    type: JSON
    value: "{{ outputs.generate_challenge_spec.vars.challenge }}"
